config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP },
            uniqueness: { case_sensitive: false }

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
  
  default_scope -> {order(updated_at: :desc)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: { maximum:140 }
  validates :recipe_id, presence: true
  validates :chef_id, presence: true

  belongs_to :chef
  belongs_to :recipe
  
  default_scope -> { order(updated_at: :desc) }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true, length: { minimum:3, maximum:20 }
  validates_uniqueness_of :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: {minimum:5, maximum:500}

  belongs_to :chef
  validates :chef_id, presence: true

  default_scope -> {order(updated_at: :desc)}
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_chef, :logged_in?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_chef
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must log in!"
      redirect_to root_path
    end
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_chef.admin?)
      flash[:danger] = "Only admins can do that!"
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :initialize_chef, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only:[:update, :edit]
  before_action :require_admin, only:[:destroy]

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @chef.update(get_chef_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to @chef
    else
      render 'chefs/edit'
    end
  end

  def create
    @chef = Chef.new(get_chef_params)
    if @chef.save
      session[:chef_id] = @chef.id
      flash[:success] = "Welcome, #{@chef.name} to MyRecipes app"
      redirect_to chef_path(@chef)
    else
      render 'chefs/new'
    end
  end

  def destroy
    unless @chef.admin?
      @chef.destroy
      flash[:danger] = "Chef was deleted with all asociated recipes"
      redirect_to chefs_path
    end
  end

  private

  def get_chef_params
    params.require(:chef).permit(:name, :email, :password, :password_confirmation)
  end

  def initialize_chef
    @chef = Chef.find(params[:id])
  end

  def require_same_user
    unless @chef == current_chef && !current_chef.admin?
      flash[:danger] = "You can only edit your profile"
      redirect_to chefs_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)
    @comment.chef = current_chef

    if @comment.save
      flash[:success] = "Comment added successfully"
      redirect_to recipe_path(@recipe)
    else
      flash[:danger] = "Comment was not saved"
      redirect_to :back
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, only: [:show, :edit, :update]

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(get_ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient created successfully"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ingredient.update(get_ingredient_params)
      flash[:notice] = "Ingredient updated successfully"
      redirect_to @ingredient
    else
      render 'edit'
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def get_ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :initialize_recipe, only:[:show, :update, :edit, :destroy]
  before_action :require_user, except:[:index, :show]
  before_action :require_same_user, only:[:update, :edit, :destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(get_recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe saved succesfully"
      redirect_to recipe_path(@recipe)
    else
      render 'recipes/new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(get_recipe_params)
      flash[:success] = "Recipe updated succesfully"
      redirect_to recipe_path(@recipe)
    else
      render 'recipes/edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted succesfully"
    redirect_to recipes_path
  end

  private

  def get_recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids:[] )
  end

  def initialize_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    unless @recipe.chef == current_chef && !current_chef.admin?
      flash[:danger] = "You can only edit your recipes"
      redirect_to recipes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    chef = Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id] = chef.id
      flash[:success] = "Your login was successfull"
      redirect_to chef
    else
      flash.now[:danger] = "Email and/or password is incorrect!"
      render 'sessions/new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.name, class: "img-circle")
  end
end

app/views/chefs/_chefs.html.erb
<% obj.each do |chef|%>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
      </section>
    </div>

    <div class="col-md-8 well">
      <%= link_to gravatar_for(chef, size: 120), chef_path(chef) %>
      <h4><%= link_to chef.name.capitalize, chef_path(chef) %></h4>
      <p><%= pluralize(chef.recipes.count, "recipe") if chef.recipes.count > 0 %></p>
      <p><%= link_to 'Delete this chef', chef_path(chef), method: :delete,
              data: {confirm: "Are you sure?"} if logged_in? && current_chef.admin? && !chef.admin? %></p>
    </div>
  </div>
  <br/>
<% end %>

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group-row">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Write your name", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", placeholder: "Write your email address", autofocus: :true %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "Write your password", autofocus: :true %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Confirm password" %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password", autofocus: :true %>
        </div>

        <div class="form-group">
          <%= f.submit(@chef.new_record? ? "Create account" : "Update account",
           class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>

    <div class="center">
      [ <%= link_to "Return to home", root_path %>]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: 'Edit your profile' %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "List of Chefs" %>

<div class='d-flex justify-content-center'><%= will_paginate %></div>
<%= render 'chefs', obj: @chefs %>
<div class='d-flex justify-content-center'><%= will_paginate %></div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: 'Sign up for recipes app' %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.name}'s profile" %>
<div class="center">
  <%= gravatar_for @chef, size: 150 %>
</div>
<br/>
<% if @chef.recipes.count > 0 %>
  <h4 align="center"><%= @chef.name.capitalize %>'s recipes</h4>
  <br/>
  <div class='d-flex justify-content-center'><%= will_paginate @chef_recipes %></div>
    <%= render 'recipes/recipe', obj: @chef.recipes %>
  <div class='d-flex justify-content-center'><%= will_paginate @chef_recipes %></div>
<% else %>
  <h4 align="center">No recipes yet</h4>
<% end %>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-2">
    <section class="chef_info center">
      <%= gravatar_for(comment.chef, size: 60) %>
    </section>
  </div>

  <div class="col-md-8">
    <p><%= comment.description %></p>
    <p>
      <span class="quiet">
        <small>Created: <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.chef.name %></small>
      </span>
    </p>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="d-flex justify-content-center">
  <%= will_paginate comments %>
</div>

<% comments.each do |comment| %>
  <%= render(partial: 'comments/comment', object: comment) %>
<% end %>

<div class="d-flex justify-content-center">
  <%= will_paginate comments %>
</div>

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group-row">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.submit(@ingredient.new_record? ? "Add new ingredient" : "Update ingredient", class: "btn btn-primary btn-lg btn-xlarge")%>
        </div>
      </div>
    <% end %>

    <div class="center">
      [ <%= link_to "Return to main page", root_path %>]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge badge-secondary"><%= link_to ingredient.name, ingredient_path(ingredient) %>&nbsp; </span>

app/views/ingredients/_ingredients.html.erb
<% obj.each do |ingredient|%>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
      </section>
    </div>

    <div class="col-md-8 well">
      <h4><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></h4>
      <p><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes.count > 0 %></p>
      <p><%= link_to 'Edit this ingredient', edit_ingredient_path(ingredient) if current_chef && current_chef.admin? %></p>
    </div>
  </div>
  <br/>
<% end %>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Edit ingredient's name" %>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available ingredients" %>

<div class='d-flex justify-content-center'><%= will_paginate %></div>
<%= render 'ingredients', obj: @ingredients %>
<div class='d-flex justify-content-center'><%= will_paginate %></div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Enter new ingredient's name" %>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name}" %>

<% if @ingredient.recipes.count > 0 %>
  <h4 align="center">Recipes containing <%= @ingredient.name %></h4>
  <br/>
  <div class='d-flex justify-content-center'><%= will_paginate %></div>
    <%= render 'recipes/recipe', obj: @ingredient_recipes %>
  <div class='d-flex justify-content-center'><%= will_paginate %></div>

<% else %>
  <h4 align="center">No recipes yet</h4>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="center alert alert-<%= name %>">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'MyRecepies', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Chefs', chefs_path, class: 'nav-link' %></a>
      </li>
      <li class="nav-item">
        <%= link_to 'All recipes', recipes_path, class: 'nav-link' %></a>
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Recipe', new_recipe_path, class: 'dropdown-item' %></a>
            <%= link_to 'All recipes', recipes_path, class: 'dropdown-item' %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ingredients
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'New ingredient', new_ingredient_path, class: 'dropdown-item' if logged_in? && current_chef.admin?%></a>
          <%= link_to 'All ingredients', ingredients_path, class: 'dropdown-item' %></a>
          <div class="dropdown-divider"></div>
          <% Ingredient.all.each do |ing| %>
            <%= link_to ing.name.capitalize, ingredient_path(ing), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-5 my-sm-0 mr-sm-5" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.name.capitalize %>'s profile
            <%= 'Admin' if current_chef.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Your profile', chef_path(current_chef), class: 'dropdown-item' %></a>
            <%= link_to 'Edit your profile', edit_chef_path(current_chef), class: 'dropdown-item' %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            <%= link_to 'Logout', logout_path, method: :destroy, class: 'dropdown-item' %>
          </div>
        </li>
      <% else%>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecepies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class='container'>
      <%= yield %>
    </div>  
  </body>
</html>

app/views/pages/home.html.erb
<div class='jumbotron center'>
  <h1>Welcome to my recepies app</h1>
  <h2>Best Recipee sharing app</h2>
  <p><%= link_to "Sign up", signup_path, class: 'btn btn-danger btn-large btn-xlarge'%></p>
</div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group-row">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", placeholder: "Write your recipe", rows: 7 %>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-offset-2 col-md-8">
              <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input-checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge", value: "Submit"%>
        </div>
      </div>
    <% end %>

    <div class="center">
      [ <%= link_to "Return to recipes list", recipes_path %>]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe|%>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>

    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>

      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>

      <p>
        <span class="quiet">
          <small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.name.capitalize %>
          | <%= pluralize(recipe.comments.count, 'Comment') %></small>
        </span>
      </p>
      <% if logged_in? && (recipe.chef == current_chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= render 'shared/recipe_actions', obj: recipe %>
        </div>
      <% end %>
    </div>
  </div>
  <br/>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit a recipe" %>
<%= render 'recipes/form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "List of all Recipes" %>

<div class='d-flex justify-content-center'><%= will_paginate %></div>
  <%= render 'recipes/recipe', obj: @recipes %>
<div class='d-flex justify-content-center'><%= will_paginate %></div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>
<%= render 'recipes/form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-offset-4">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr/>

  <div align="left">
    <%= simple_format(@recipe.description) %>
    <% if @recipe.ingredients.any? %>
      <p>Ingredients: <%= render @recipe.ingredients%></p>
    <% end %>
    <hr/>
    
    <div class="center"> <em>Created by:</em>
      <p>
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
      </p>
      <small><%= @recipe.chef.name.capitalize %></small>
    </div>
  </div>
  
  <div align="right">Created: <%= time_ago_in_words(@recipe.created_at) %> ago</div>

  <div class="recipe-actions">
    <% if logged_in? && (@recipe.chef == current_chef || current_chef.admin?) %>
      <%= render 'shared/recipe_actions', obj: @recipe%>
    <% end %>
    <%= link_to 'Return to recipes list', recipes_path, class: 'btn btn-xs btn-primary'%>
  </div>
</div>
<br/>

<% if logged_in? %>
  <div class="row">
    <br/>
      <div class="col-md-12">
        <%= form_for([@recipe, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <div class="form-group-row">
            <div class="form-group">
              <%= f.label :description, 'Comment' %>
              <%= f.text_area :description, class: "form-control", placeholder: "Enter comment", rows: 5 %>
            </div>

            <div class="form-group">
              <%= f.submit class: "btn btn-primary btn-lg btn-xlarge", value: "Submit comment"%>
            </div>
          </div>
        <% end %>
      </div>
    <br/>
  </div>
<% end %>

<% if @recipe.comments.count > 0 %>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h3>Comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No comments yet</h3>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="card bg-danger">
    <h2 class="panel-title">
      <%= pluralize(obj.errors.count, 'error') %>
      stopped this <%= obj.class %> from being saved:
    </h2>

    <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr/>

app/views/shared/_recipe_actions.html.erb
<%= link_to 'Edit this recipe', edit_recipe_path(obj), class: 'btn btn-xs btn-warning' %>
      <%= link_to 'Delete this recipe', recipe_path(obj), method: :delete, 
                                                              data: { confirm: 'Are you sure?'},
                                                              class: 'btn btn-xs btn-danger' %>